FROM openjdk:11

WORKDIR /app

COPY target/app.jar /app/cook-book.jar

EXPOSE 8083

ENV spring.main.allow-bean-definition-overriding=true
ENV spring.freemarker.template-loader-path=classpath:/templates
ENV spring.freemarker.suffix=.ftlh
ENV server.servlet.context-path=/app
ENV JAVA_HOME="C:\Program Files\Java\jdk1.8.0_202"
ENV PATH="C:\Program Files\Java\jdk1.8.0_202\bin"

CMD ["java", "-jar", "cook-book.jar"]